Repository HoTT/Coq-HoTT, pull requests merged in 2020-02, with the labels that each got.

#1215 dropped support for systems without autoconf
  .travis.yml
  autogen.sh
  etc/ci/after_success.sh
  etc/ci/autogen_and_push.sh
  etc/ci/before_script.sh
Labels: scripts, travis

#688 Add some tactics for globally-nameless proving style
  _CoqProject
  theories/Basics/Overture.v
  theories/HoTT.v
  theories/Tactics/Nameless.v
Labels: tactics

#1219 fixed #817
  theories/Modalities/ReflectiveSubuniverse.v
Labels: bugfix

#1218 replaced ap2 with ap011 and removed ap2
  theories/Basics/Overture.v
  theories/Basics/PathGroupoids.v
  theories/Classes/implementations/field_of_fractions.v
  theories/Classes/implementations/natpair_integers.v
  theories/Classes/implementations/peano_naturals.v
  theories/Classes/isomorphisms/rings.v
  theories/Classes/tactics/ring_pol.v
  theories/Classes/tactics/ring_quote.v
  theories/Classes/theory/rings.v
  theories/Cubical/PathCube.v
  theories/Cubical/PathSquare.v
  theories/Spaces/Torus/TorusEquivCircles.v
  theories/Types/Prod.v
Labels: cleanup

#1225 AbelianGroup.v: simplify some proofs and avoid Univalence; fix typos
  theories/Algebra/AbelianGroup.v
Labels: group theory

#1216 removed funext from proof of O_inverts_functor_sigma_to_SepO
  theories/Modalities/ReflectiveSubuniverse.v
Labels: bug, task

#1251 [HoTTBookExercises] Regenerate from latest book
  contrib/HoTTBookExercises.v
Labels: exercises

#1248 Import IsGraph-as-a-parameter from wildcat branch
  theories/Algebra/Group.v
  theories/Basics/Notations.v
  theories/Homotopy/Suspension.v
  theories/Pointed.v
  theories/Pointed/pType.v
  theories/WildCat/Core.v
  theories/WildCat/EmptyCat.v
  theories/WildCat/Equiv.v
  theories/WildCat/EquivGpd.v
  theories/WildCat/Forall.v
  theories/WildCat/FunctorCat.v
  theories/WildCat/Induced.v
  theories/WildCat/NatTrans.v
  theories/WildCat/Opposite.v
  theories/WildCat/Paths.v
  theories/WildCat/Prod.v
  theories/WildCat/Sigma.v
  theories/WildCat/Sum.v
  theories/WildCat/Type.v
  theories/WildCat/UnitCat.v
  theories/WildCat/Yoneda.v
Labels: wildcat

#1246 bundled up equivalences in cubical library
  theories/Cubical/DPath.v
  theories/Cubical/DPathCube.v
  theories/Cubical/DPathSquare.v
  theories/Cubical/PathCube.v
  theories/Cubical/PathSquare.v
  theories/Homotopy/Suspension.v
  theories/Modalities/Separated.v
  theories/Spaces/Torus/TorusEquivCircles.v
Labels: cleanup

#1254 Modulo map for Fin
  theories/Spaces/Finite.v
Labels: feature

#1268 stopped jobs from getting cancelled
  .github/workflows/ci.yml
Labels: ci
