Repository HoTT/Coq-HoTT, pull requests merged in 2020-08, with the labels that each got.

#1376 fix fragile-hint-constr warning
  coq/theories/Init/Notations.v
  coq/theories/Init/Peano.v
  theories/Basics/Overture.v
  theories/Categories/Adjoint/Composition/AssociativityLaw.v
  theories/Categories/Adjoint/Composition/IdentityLaws.v
  theories/Categories/Category/Core.v
  theories/Categories/Category/Morphisms.v
  theories/Categories/Functor/Composition/Laws.v
  theories/Categories/Functor/Core.v
  theories/Categories/NaturalTransformation/Core.v
  theories/Categories/PseudonaturalTransformation/Core.v
Labels: cleanup, compiler warning

#1378 small optimization to PathCube.v
  theories/Cubical/PathCube.v
Labels: cubical, optimization

#1381 added Zulip badge to README.md
  README.md
Labels: documentation

#1382 [Overture] Get discriminate working
  theories/Basics/Overture.v
  theories/Tests.v
Labels: tactics

#1386 remove extra exports in wildcat library
  theories/Algebra/ooGroup.v
  theories/WildCat/Paths.v
  theories/WildCat/Type.v
  theories/WildCat/Yoneda.v
Labels: cleanup

#1385 removed "oo" notation for purely
  theories/Homotopy/ExactSequence.v
  theories/Truncations/Core.v
Labels: cleanup

#1391 Added link to actions page for github actions branch
  README.md
Labels: documentation
